services:
  Flask-App:
    image: flask-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5056:5056"
    volumes:
     - type: bind
       source: .
       target: /app
  Linter-Test:
    image: linter-test
    build:
      context: .
      dockerfile: Dockerfile
      target: Linter-Test
    volumes:
     - type: bind
       source: .
       target: /app
