services:
  server:
    image: app-server
    build: 
      context: ./Server
    ports:
      - "2024:2024"
    environment:
      - Url=mongodb://mongo:27017/testFrienemie
    volumes:
      - ./Server:/app
    command: npm start

  clint-dev:
    image: app-clint-dev
    build: 
      context: ./Clint
      target: dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:2024
    # volumes:
    #   - ./Clint:/app
    command: npm start -- --host 0.0.0.0

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
