FROM node:18-alpine as base

# install Dependencies
WORKDIR /app
COPY package*.json ./
RUN npm install

# Run Production Build
FROM base as production
COPY . .
EXPOSE 2024
CMD ["npm", "run", "build"]

# Production server
FROM node:20-slim AS prod

WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev

# Copy built frontend from build stage
COPY --from=build /app/dist ./dist
CMD ["npx", "serve", "dist"]

# Local Development Server
FROM base as dev
COPY . .
CMD ["npm", "start", "--", "--host", "0.0.0.0"]