FROM node:18-alpine as base

# install Dependencies
WORKDIR /app
COPY package*.json ./
RUN npm install nodemon -g
RUN npm install

# copy all files
COPY . .
EXPOSE 2024
CMD ["npm", "start"]