name: Deploy to Production
on:
  push:
    branches:
      - main

env:
  SERV_PUBLIC_IP: ${{ secrets.SERV_PUBLIC_IP }}
  SERV_SSH_KEY: ${{ secrets.SERV_SSH_KEY }}
  SERV_SSH_PORT: ${{ secrets.SERV_SSH_PORT }}
  USERNAME: ${{ secrets.USERNAME }}
  APP_DIR: App

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERV_SSH_KEY }}
      
      # - name: Add server to known_hosts
      #   run: |
      #     ssh-keyscan -p $SERV_SSH_PORT $SERV_PUBLIC_IP >> ~/.ssh/known_hosts

      - name: Login and Deploy
        run: |
          echo "${{ secrets.SERV_SSH_KEY }}" > /tmp/deploy_key
          chmod 600 /tmp/deploy_key
          ssh -o StrictHostKeyChecking=no -p $SERV_SSH_PORT -i /tmp/deploy_key $USERNAME@$SERV_PUBLIC_IP "echo 'Login successful!'"

            git clone https://github.com/sakibtalukqder/Linter-Test.git
            
            cd Linter-Test/
            git pull origin main
            ls -la
            hostname
            pwd
            ip a
            # Docker image build
            docker compose build Flask-App

            # Container deploy (up + recreate)
            docker compose up Flask-App
